# If elif else

In [1]:
exam_score = int(input("Enter score: "))

if exam_score >= 40:
    print('passed...! Cheers')

Enter score: 56
passed...! Cheers


In [2]:
exam_score = int(input("Enter score: "))

if exam_score >= 40:
    print('passed...! Cheers')
else:
    print('Better luck!')

Enter score: 48
passed...! Cheers


In [3]:
score = int(input("Enter score: "))

if score >0:
    print(' +ve Number')
elif score == 0:
    print('zero')
else:
    print('-ve number')

Enter score: 3
 +ve Number


# For Loop

In [4]:
for i in range(0, 10):
    print(i)

0
1
2
3
4
5
6
7
8
9


In [5]:
print(list(range(10)))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


In [6]:
print(list(range(0,11,2)))

[0, 2, 4, 6, 8, 10]


In [7]:
for i in range(0, 10):
    print(i)
else:
    print("empty items")

0
1
2
3
4
5
6
7
8
9
empty items


In [8]:
list1 = [1,2,3,4,5,6,7,8,9,10]

for i in list1:
    print(i)

1
2
3
4
5
6
7
8
9
10


In [9]:
companies = ['apple', 'microsoft', 'facebook', 'tesla', 'google', 'walmart', 'jersey']

for i in companies:
    print(i)
    if i == 'google':
        continue                #can use break to stop iteration

apple
microsoft
facebook
tesla
google
walmart
jersey


In [10]:
val1 = 15
val2 = 50

for i in range(val1, val2+1):
    if i > 1:
        for num in range(2,i):
            if (i%num) == 0:
                break
            else:
                print(i)

15
17
17
17
17
17
17
17
17
17
17
17
17
17
17
17
19
19
19
19
19
19
19
19
19
19
19
19
19
19
19
19
19
21
23
23
23
23
23
23
23
23
23
23
23
23
23
23
23
23
23
23
23
23
23
25
25
25
27
29
29
29
29
29
29
29
29
29
29
29
29
29
29
29
29
29
29
29
29
29
29
29
29
29
29
29
31
31
31
31
31
31
31
31
31
31
31
31
31
31
31
31
31
31
31
31
31
31
31
31
31
31
31
31
31
33
35
35
35
37
37
37
37
37
37
37
37
37
37
37
37
37
37
37
37
37
37
37
37
37
37
37
37
37
37
37
37
37
37
37
37
37
37
37
39
41
41
41
41
41
41
41
41
41
41
41
41
41
41
41
41
41
41
41
41
41
41
41
41
41
41
41
41
41
41
41
41
41
41
41
41
41
41
41
43
43
43
43
43
43
43
43
43
43
43
43
43
43
43
43
43
43
43
43
43
43
43
43
43
43
43
43
43
43
43
43
43
43
43
43
43
43
43
43
43
45
47
47
47
47
47
47
47
47
47
47
47
47
47
47
47
47
47
47
47
47
47
47
47
47
47
47
47
47
47
47
47
47
47
47
47
47
47
47
47
47
47
47
47
47
47
49
49
49
49
49


# While Loop

In [12]:
num=10
add=0

i=1

while i<=num:
    add=add+i
    i=i+1
    print(i)
print("Addition",add)

2
3
4
5
6
7
8
9
10
11
Addition 55


# Pass Statement

In [13]:
def example():
    pass

# Python Packages

In [ ]:
1- Numpy
2- Pandas
3- Seaborn
4- Sklearn
5- Matplotlib
6- Requests
7- NLTK

# Numpy

In [15]:
import numpy as np

In [16]:
list1= [1,2,3]

In [17]:
type(list1)

list

In [18]:
arr = np.array(list1)

In [19]:
arr

array([1, 2, 3])

In [20]:
type(arr)

numpy.ndarray

In [21]:
arr.ndim

1

# Built in Methods

In [22]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [23]:
np.arange(5,20)

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [24]:
np.arange(5,20,5)

array([ 5, 10, 15])

In [25]:
np.arange(5,20, dtype=float)

array([ 5.,  6.,  7.,  8.,  9., 10., 11., 12., 13., 14., 15., 16., 17.,
       18., 19.])

# Zeros & Ones

In [26]:
np.zeros(4)

array([0., 0., 0., 0.])

In [27]:
np.zeros(4, dtype=int)

array([0, 0, 0, 0])

In [29]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [30]:
np.ones(3)

array([1., 1., 1.])

In [31]:
np.ones(3, dtype=int)

array([1, 1, 1])

In [32]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

# Linspace

In [34]:
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [37]:
np.linspace(0,50,6)

array([ 0., 10., 20., 30., 40., 50.])

# Eye

In [38]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [39]:
np.eye(4,5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.]])